# Generated by Django 2.2.24 on 2021-08-16 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ListaAtualizaEndereco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='NomeMae',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dataCadastro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='datanascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
